@echo off
cls
color e
title Spotify Debloater + Ad removal tool
choice /n /m Do you want to debloat Spotify and have a break from the ads... forever? [Y/N]
if errorlevel 1 (
    echo.
    echo $ Downloading Spotify + blocking ads and debloating it..
    %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12}"; "& {(Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/SpotX-CLI/SpotX-Win/main/Install.ps1').Content | Invoke-Expression}"
    echo $ Installation done.
    echo $ Terminating Spotify if it's running...
    taskkill /f /im spotify.exe
    echo $ Debloating...
    del /f /q /s "%appdata%\Spotify\SpotifyMigrator.exe"
    del /f /q /s "%appdata%\Spotify\SpotifyStartupTask.exe"
    del /f /q /s "%appdata%\Spotify\Apps\Buddy-list.spa"
    del /f /q /s "%appdata%\Spotify\Apps\Concert.spa"
    del /f /q /s "%appdata%\Spotify\Apps\Concerts.spa"
    del /f /q /s "%appdata%\Spotify\Apps\Error.spa"
    del /f /q /s "%appdata%\Spotify\Apps\Findfriends.spa"
    del /f /q /s "%appdata%\Spotify\Apps\Legacy-lyrics.spa"
    del /f /q /s "%appdata%\Spotify\Apps\Lyrics.spa"
    del /f /q /s "%appdata%\Spotify\Apps\Show.spa"
    del /f /q /s "%appdata%\Spotify\Apps\Buddy-list.spa"
    del /f /q /s "%appdata%\Spotify\locales\am.pak"
    del /f /q /s "%appdata%\Spotify\locales\ar.mo"
    del /f /q /s "%appdata%\Spotify\locales\ar.pak"
    del /f /q /s "%appdata%\Spotify\locales\bg.pak"
    del /f /q /s "%appdata%\Spotify\locales\bn.pak"
    del /f /q /s "%appdata%\Spotify\locales\ca.pak"
    del /f /q /s "%appdata%\Spotify\locales\cs.mo"
    del /f /q /s "%appdata%\Spotify\locales\cs.pak"
    del /f /q /s "%appdata%\Spotify\locales\da.pak"
    del /f /q /s "%appdata%\Spotify\locales\de.mo"
    del /f /q /s "%appdata%\Spotify\locales\de.pak"
    del /f /q /s "%appdata%\Spotify\locales\el.mo"
    del /f /q /s "%appdata%\Spotify\locales\el.pak"
    del /f /q /s "%appdata%\Spotify\locales\en-GB.pak"
    del /f /q /s "%appdata%\Spotify\locales\es.mo"
    del /f /q /s "%appdata%\Spotify\locales\es.pak"
    del /f /q /s "%appdata%\Spotify\locales\es-419.mo"
    del /f /q /s "%appdata%\Spotify\locales\es-419.pak"
    del /f /q /s "%appdata%\Spotify\locales\et.pak"
    del /f /q /s "%appdata%\Spotify\locales\fa.pak"
    del /f /q /s "%appdata%\Spotify\locales\fi.mo"
    del /f /q /s "%appdata%\Spotify\locales\fi.pak"
    del /f /q /s "%appdata%\Spotify\locales\fil.pak"
    del /f /q /s "%appdata%\Spotify\locales\fr.mo"
    del /f /q /s "%appdata%\Spotify\locales\fr.pak"
    del /f /q /s "%appdata%\Spotify\locales\fr-CA.mo"
    del /f /q /s "%appdata%\Spotify\locales\gu.pak"
    del /f /q /s "%appdata%\Spotify\locales\he.mo"
    del /f /q /s "%appdata%\Spotify\locales\he.pak"
    del /f /q /s "%appdata%\Spotify\locales\hi.pak"
    del /f /q /s "%appdata%\Spotify\locales\hr.pak"
    del /f /q /s "%appdata%\Spotify\locales\hu.mo"
    del /f /q /s "%appdata%\Spotify\locales\hu.pak"
    del /f /q /s "%appdata%\Spotify\locales\id.mo"
    del /f /q /s "%appdata%\Spotify\locales\id.pak"
    del /f /q /s "%appdata%\Spotify\locales\it.mo"
    del /f /q /s "%appdata%\Spotify\locales\it.pak"
    del /f /q /s "%appdata%\Spotify\locales\ja.mo"
    del /f /q /s "%appdata%\Spotify\locales\ja.pak"
    del /f /q /s "%appdata%\Spotify\locales\kn.pak"
    del /f /q /s "%appdata%\Spotify\locales\ko.mo"
    del /f /q /s "%appdata%\Spotify\locales\ko.pak"
    del /f /q /s "%appdata%\Spotify\locales\lt.pak"
    del /f /q /s "%appdata%\Spotify\locales\lv.pak"
    del /f /q /s "%appdata%\Spotify\locales\ml.pak"
    del /f /q /s "%appdata%\Spotify\locales\mr.pak"
    del /f /q /s "%appdata%\Spotify\locales\ms.mo"
    del /f /q /s "%appdata%\Spotify\locales\ms.pak"
    del /f /q /s "%appdata%\Spotify\locales\nb.pak"
    del /f /q /s "%appdata%\Spotify\locales\nl.mo"
    del /f /q /s "%appdata%\Spotify\locales\nl.pak"
    del /f /q /s "%appdata%\Spotify\locales\pl.mo"
    del /f /q /s "%appdata%\Spotify\locales\pl.pak"
    del /f /q /s "%appdata%\Spotify\locales\pt-PT.pak"
    del /f /q /s "%appdata%\Spotify\locales\pt-BR.pak"
    del /f /q /s "%appdata%\Spotify\locales\pt-BR.mo"
    del /f /q /s "%appdata%\Spotify\locales\ro.pak"
    del /f /q /s "%appdata%\Spotify\locales\ru.mo"
    del /f /q /s "%appdata%\Spotify\locales\ru.pak"
    del /f /q /s "%appdata%\Spotify\locales\sk.pak"
    del /f /q /s "%appdata%\Spotify\locales\sl.pak"
    del /f /q /s "%appdata%\Spotify\locales\sr.pak"
    del /f /q /s "%appdata%\Spotify\locales\sv.mo"
    del /f /q /s "%appdata%\Spotify\locales\sv.pak"
    del /f /q /s "%appdata%\Spotify\locales\sw.pak"
    del /f /q /s "%appdata%\Spotify\locales\ta.pak"
    del /f /q /s "%appdata%\Spotify\locales\te.pak"
    del /f /q /s "%appdata%\Spotify\locales\th.mo"
    del /f /q /s "%appdata%\Spotify\locales\th.pak"
    del /f /q /s "%appdata%\Spotify\locales\tr.mo"
    del /f /q /s "%appdata%\Spotify\locales\tr.pak"
    del /f /q /s "%appdata%\Spotify\locales\uk.pak"
    del /f /q /s "%appdata%\Spotify\locales\vi.mo"
    del /f /q /s "%appdata%\Spotify\locales\vi.pak"
    del /f /q /s "%appdata%\Spotify\locales\zh-CN.pak"
    del /f /q /s "%appdata%\Spotify\locales\zh-Hant.mo"
    del /f /q /s "%appdata%\Spotify\locales\zh-TW.pak"
    reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "Spotify" /f
    cls
    echo $ All done. Press any key to exit.
    pause >nul
) else (
    echo.
    echo $ No changes have been made. Press any key to exit.
    pause >nul & exit
)
